export const actions = {
    profile: {
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
        USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
        IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
        USER_DATA_UPDATED: "USER_DATA_UPDATED",
        BLOGS: "BLOGS",
        BIO_EDITED: "BIO_EDITED",
    },
    blog: {
        DATA_FETCHING: "POST_DATA_FETCHING",
        DATA_FETCHED: "POST_DATA_FETCHED",
        DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
        DATA_CREATED: "POST_DATA_CREATED",
        DATA_EDITED: "POST_DATA_EDITED",
        POST_DELETED: "POST_DATA_DELETED",
        DATA_FETCHED_FAVOURTIE: "DATA_FETCHED_FAVOURITE",
        DATA_FETCHING_POPULAR: "DATA_FETCHING_POPULAR",
        POST_CREATED: "POST_CREATED",
    },
};